name: Build Navigator

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Build
      run: |
        cd navigator
        yarn
        yarn run build
    - name: Lint
      run: |
        cd navigator
        yarn run eslint:check
        yarn run prettier:check

