name: Publish Package

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine jupyterlab
      - name: Build and publish NPM package
        if: ${{ startsWith(github.ref, 'jupyterlab_conda') }}
        run: |
          echo $DUMMY
          cd labextension
          jlpm
          npm publish
          cd ..
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          DUMMY: ${{ github.ref }}
      - name: Publish Python package
        if: ${{ !startsWith(github.ref, 'jupyterlab_conda') }}
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
          DUMMY: ${{ github.ref }}
        run: |
          echo $DUMMY
          python setup.py sdist bdist_wheel
          twine upload dist/*
